<h1 style="font-size: 36px; color: #FFD700">2 - TENSORS</h1>

Tensor là một cấu trúc dữ liệu rất giống với mảng và ma trận, trong pytorch, tensor để mã hóa input và output, tham số models

Tensor tương tự như ndarray của Numpy, ngoại từ việc tensor có thể chạy trên GPU/ accelerators. Tensor và numpy có thể chia sẻ chung bộ nhớ cơ bản.

Tensor cũng được tối ưu để phân biệt tự động.

In [2]:
import torch 
import numpy as np

Khởi tạo một tensor

In [4]:
# trực tiếp từ data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)

In [5]:
# từ một np array và ngược lại
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

Tensor giữ nguyên thuộc tính (shape, datatype) trừ khi bị ghi đè một cách rõ ràng

In [6]:
# từ một tensors khác
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n") # giữ nguyên properties

x_rand = torch.rand_like(x_data, dtype=torch.float) # override datatype của x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7871, 0.4261],
        [0.7189, 0.0804]]) 



shape là một bộ các chiều tensor.

In [9]:
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor}\n")
print(f"Ones Tensor: \n {ones_tensor}\n")
print(f"Zeros Tensor: \n {zeros_tensor}\n")

Random Tensor: 
 tensor([[0.4253, 0.6956, 0.7985],
        [0.4851, 0.9953, 0.8891]])

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])



Thuộc tính tensor mô tả: shape, datatype, device

In [10]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


CÁC PHÉP TOÁN TRÊN TENSOR

Hơn 1200 phép toán tensor
- số học
- đại số tuyến tính
- thao tác ma trận (chuyển vị, lập chỉ mục, cắt lát)
- lấy mẫu
- ...


Theo mặc định, tensor trên đc tạo trên CPU, ta cần di chuyển rõ ràng các tensor đến accelerator bằng .to sau khi ktra tính khả dụng của device. 

Việc sao chép các tensor lớn trên các thiết bị có thể tốn kém về thgian và memory

In [11]:
# di chuyển tensor đến accelerator nếu nó khả dụng
if torch.accelerator.is_available():
    tensor = tensor.to(torch.accelerator.current_accelerator())

Lập chỉ mục và cắt lát theo chuẩn numpy

In [51]:
tensor = torch.ones(4, 4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}") # cách này gioogns tensor[:, -1]
tensor[:,1] = 0 
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


Nối các tensor: Sử dụng torch.cat để nối một chuối tensor theo một dọc theo một chiều nhất định

In [18]:
t1 = torch.cat([tensor, tensor, tensor], dim = 1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


- Nối bằng torch.stack 

In [25]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([4, 5, 6])
c = torch.tensor([7, 8, 9])

result_1 = torch.stack([a, b, c], dim=0)
print(f"Joining tensor, dim= 0: \n {result_1}") # các tensor xếp ngang qua
result_2 = torch.stack([a, b, c], dim=1)
print(f"Joining tensor, dim= 1: \n {result_2}") # các tensor xếp dọc xuống

Joining tensor, dim= 0: 
 tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Joining tensor, dim= 1: 
 tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


CÁC PHÉP TÍNH SỐ HỌC

In [37]:
# Phép nhân ma trận giữa 2 tensor
y1 = tensor @ tensor.T 
y2 = tensor.matmul(tensor.T) 

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

Tenser một phần tử: Ta có thể chuyển đổi tensor một phần tử thành một giá trị số python bằng item()

In [39]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

tensor(12.)
12.0 <class 'float'>


IN-PLACE OPERATOR

Các hoạt động lưu trữ kết quả vào toán hạng được gọi là in-place. Chúng được biểu thị bằng hậu tố _ . Vd: x.copy_(y), x.t_() sẽ thay đổi x

In [56]:
a_tensor = tensor.add_(5)
print(tensor)
print("\n")
print(a_tensor)

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


- Các hoạt động tại chỗ tiết kiệm một số bộ nhớ, nhưng có thể gây ra vấn đề khi tính toán các đạo hàm do mất lịch sử ngay lập tức.

Cầu nối với numpy

In [57]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


- Sự thay đổi trong tensor sẽ phản ánh trong mảng np

In [58]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [61]:
n = np.ones(5)
t = torch.from_numpy(n)

In [62]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


Tương tự thì những phán ánh trong mảng Numpy sẽ đc phản ánh trong tensor